# Copyright (c) 2026 ZyvorAI Labs Private Limited.
# SPDX-License-Identifier: Apache-2.0
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: atlas-dr-mirror-test
  namespace: rook-ceph
spec:
  failureDomain: osd
  replicated:
    size: 1
    requireSafeReplicaSize: false
  mirroring:
    enabled: true
    mode: image
---
apiVersion: ceph.rook.io/v1
kind: CephRBDMirror
metadata:
  name: atlas-dr-mirror
  namespace: rook-ceph
spec:
  count: 1
  resources:
    limits: { memory: 1Gi }
